### PR TITLE
Update pydantic

### PR DESCRIPTION
**Pull request by danielamar101**
This is mainly to update to pydantic v2 and have a new dependency set. I haven't tested anything other than the recognize track functionality.

### CODE REVIEW

**Comment by danielamar101** [comment]
Hey @dotX12 can we get this in? It's sort of blocking my ability to have this library in my client without resolution issues. I have been getting around it with an editable install but would be easier to get an official version tagged and cut. 

Let me know if I can help out in any way to make the process easier or if there is anything else I need to do/edit. It goes without saying we all tremedously appreciate your work on this API.

**Comment by bar3hrv** [comment]
> 

is it possible to make a fork with the improved version of shazamio?

**Comment by dotX12** [comment]
Thanks for the input, hopefully I'll make those changes tomorrow!

**Comment by dotX12** [comment]
The numpy version has been updated to 2.1.2, the current release requires a minimum of Python3.10, as numpy 2.1.2 requires a minimum of Python 3.10.

**Review by dotX12 — APPROVED** [review]

**Pull request merged**
