### PR TITLE
Add devcontainer and move test dependencies to dev deps

### PR DESCRIPTION
**Pull request by jam-girl**
# Overview 
Moved `pytest` and `pytest-asyncio`to dev dependencies. Added a dev container including `ffmpeg` so one could immediately be up and running with a compatible developer environment for this project.

## Evidence 
Screenshot 2024-03-31 at 12 49 55

### CODE REVIEW

**Comment by jam-girl** [comment]
Apologies that this isn't an atomic PR and does two things, if you want me to break it up between the `dependency move and the version upgrade` and the `devcontainer` please let me know

**Comment by dotX12** [comment]
I have never used the devcontainers tool, but if it is useful for you and other people for development, why not.

**Comment by dotX12** [comment]
> Apologies that this isn't an atomic PR and does two things, if you want me to break it up between the `dependency move and the version upgrade` and the `devcontainer` please let me know

Everything is fine)

**Comment by dotX12** [comment]
I'll move this PR to dev 2.0 as there are too few changes for 0.6.0, within a week there will probably be some code, then I'll move it to master and release it.

**Pull request merged**
